us_cities = [#'Hartford',
             #'New Haven',
             # 'Washington, DC',
             # 'Fort Lauderdale',
             # 'Gainesville',
             # 'Miami',
             # 'Miami Beach',
             # 'Orlando',
             # 'Tampa',
             # 'Atlanta',
             # 'Savannah',
             # 'Honolulu',
             # 'Lahaina',
             # 'Iowa City',
             # 'Boise',
             # 'Chicago',
             # 'Evanston',
             # 'Naperville',
             # 'Schaumburg',
             # 'Skokie',
             'Bloomington',
             'Indianapolis',
             'Louisville',
             'New Orleans',
             'Allston',
             'Boston',
             'Brighton',
             'Brookline',
             'Cambridge',
             'Somerville',
             'Baltimore',
             'Ann Arbor',
             'Detroit',
             'Minneapolis',
             'Saint Paul',
             'Kansas City',
             'Saint Louis',
             'Charlotte',
             'Durham',
             'Raleigh',
             'Newark',
             'Princeton',
             'Albuquerque',
             'Santa Fe',
             'Las Vegas',
             'Reno',
             'Brooklyn',
             'Long Island City',
             'New York',
             'Flushing',
             'Cincinnati',
             'Cleveland',
             'Columbus',
             'Portland',
             'Salem',
             'Philadelphia',
             'Pittsburgh',
             'Providence',
             'Charleston',
             'Memphis',
             'Nashville',
             'Austin',
             'Dallas',
             'Houston',
             'San Antonio',
             'Salt Lake City',
             'Alexandria',
             'Arlington',
             'Richmond',
             'Burlington',
             'Bellevue',
             'Redmond',
             'Seattle',
             'Madison',
             'Milwaukee']

# preferred professionals from Jones autocomplete
# https://docs.google.com/document/d/1wVd-mEzkeTSLzDz00v91TuOAZMRvmklUc5GxNJTqKgM/edit?ts=5c73b32a
professions = [
    "architect",
    "tree-trimming",
    "home-improvement",
    "construction",
    "concrete-construction",
    "remodelling",
    "welding",
    "plumbing",
    "electrician",
    "roofing-siding-gutters",
    "tile-stone-and-flooring",
    "tree-removal",
    "waterproofing",
    "window-treatment-installation",
    "plastering-and-drywall",
    "painting-and-wallpapering",
    "metal-erection",
    "lawn-irrigation-or-sprinkler-system-installation",
    "artisan-contractor",
    "debris-removal",
    "furniture-or-fixture-installation",
    "home-builder",
    "lawn-care",
    "janitorial-services-franchise-business",
    "janitorial-services-non-franchise",
    "interior-decorator",
    "interior-sign-lettering-and-painting",
    "home-appliance-installation",
    "home-inspector",
    "handyman",
    "home-cleaning",
    "hvac-technician",
    "glass-tinting-building",
    "general-contractor",
    "carpenter",
    "landscape-architect",
    "architects-architecture-services",
    "inspector",
    "locksmith",
    "window-decorator",
    "fence-installation"]

yelp_professions = [
    "artificialturf",
    "buildingsupplies",
    "cabinetry",
    "carpenters",
    "carpetinstallation",
    "carpeting",
    "childproofing",
    "chimneysweeps",
    "contractors",
    "countertopinstall",
    "damagerestoration",
    "decksrailing",
    "demolitionservices",
    "doorsales",
    "drywall",
    "electricians",
    "excavationservices",
    "fencesgates",
    "fireprotection",
    "fireplace",
    "firewood",
    "flooring",
    "foundationrepair",
    "furnitureassembly",
    "garage_door_services",
    "gardeners",
    "glassandmirrors",
    "groutservices",
    "gutterservices",
    "handyman",
    "hvac",
    "seasonaldecorservices",
    "homeautomation",
    "homecleaning",
    "homeenergyauditors",
    "home_inspectors",
    "homenetworkinstall",
    "home_organization",
    "hometheatreinstallation",
    "homewindowtinting",
    "housesitters",
    "insulationinstallation",
    "interiordesign",
    "isps",
    "irrigation",
    "locksmiths",
    "landscapearchitects",
    "landscaping",
    "lawnservices",
    "lighting",
    "masonry_concrete",
    "mobile_home_repair",
    "movers",
    "packingservices",
    "painters",
    "patiocoverings",
    "plumbing",
    "backflowservices",
    "poolservice",
    "poolcleaners",
    "pressurewashers",
    "realestate",
    "roofing",
    "saunainstallation",
    "securitysystems",
    "blinds",
    "shutters",
    "vinylsiding",
    "solarinstallation",
    "solarpanelcleaning",
    "structuralengineers",
    "stucco",
    "televisionserviceproviders",
    "tiling",
    "treeservices",
    "utilities",
    "electricitysuppliers",
    "naturalgassuppliers",
    "watersuppliers",
    "wallpapering",
    "waterheaterinstallrepair",
    "waterpurification",
    "waterproofing",
    "windowwashing",
    "windowsinstallation"
]
